### PR TITLE
flesh out script to update Lmod cache

### LINKED ISSUE #165: WRF not available on Skylake_avx512 (temporary?)
WRF could not be found as a module; both on a running login node and on a fresh started compute node:
```[EESSI pilot 2021.12] $ ml load WRF
Lmod has detected the following error:  The following module(s) are unknown: "WRF"                                                                                                                                                  
Please check the spelling or version number. Also try "module spider ..."
It is also possible your cache file is out-of-date; it may help to try:
  $ module --ignore_cache load "WRF"                                                                                                                                                                                                
Also make sure that all modulefiles written in TCL start with the string #%Module                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
[EESSI pilot 2021.12] $ module --ignore_cache load "WRF"
[EESSI pilot 2021.12] $ which wrf.exe
/cvmfs/pilot.eessi-hpc.org/versions/2021.12/software/linux/x86_64/intel/skylake_avx512/software/WRF/3.9.1.1-foss-2020a-dmpar/WRFV3/main/wrf.exe```

### PR DESCRIPTION
**Pull request by boegel**
This makes things a bit more modular.

I used the `update_lmod_cache.sh` script to create the tarballs to fix #165

### CODE REVIEW

File: update_lmod_cache.sh [hunk 1]
```diff
@@ -0,0 +1,35 @@
+#!/bin/bash
+#
+# Script to update Lmod cache in EESSI
+#
+
+source utils.sh
```
Comment (ocaisa) [inline update_lmod_cache.sh:6]: Probably need to ensure we can pick this up from the same directory as the script (so use `$TOPDIR`)

File: EESSI-pilot-install-software.sh [hunk 2]
```diff
@@ -339,16 +312,7 @@ if [ ! -f $LMOD_RC ]; then
...
-# that update_lmod_system_cache_files updates correct Lmod cache
-lmod_cache_dir=${EASYBUILD_INSTALLPATH}/.lmod/cache
-lmod_cache_timestamp_file=${EASYBUILD_INSTALLPATH}/.lmod/cache/timestamp
-modpath=${EASYBUILD_INSTALLPATH}/modules/all
-
-${LMOD_DIR}/update_lmod_system_cache_files -d ${lmod_cache_dir} -t ${lmod_cache_timestamp_file} ${modpath}
-check_exit_code $? "Lmod cache updated" "Lmod cache update failed!"
-
-ls -lrt ${EASYBUILD_INSTALLPATH}/.lmod/cache
+./update_lmod_cache.sh ${EPREFIX} ${EASYBUILD_INSTALLPATH}
```
Comment (ocaisa) [inline EESSI-pilot-install-software.sh:315]: Careful with the use of `./`, use `$TOPDIR`

File: EESSI-pilot-install-software.sh [hunk 3]
```diff
@@ -5,34 +5,7 @@
...
-    ok_msg=$2
-    fail_msg=$3
-
-    if [[ $ec -eq 0 ]]; then
-        echo_green "${ok_msg}"
-    else
-        fatal_error "${fail_msg}"
-    fi
-}
+source utils.sh
```
Comment (ocaisa) [inline EESSI-pilot-install-software.sh:8]: Probably need to ensure we can pick this up from the same directory as the script (so use `$TOPDIR`)

**Review by ocaisa — CHANGES_REQUESTED** [review]

**Review by ocaisa — APPROVED** [review]
LGTM
